apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-example
  labels:
    app: node-example
    apm-enabled: "true"
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "node-example"
    tags.datadoghq.com/version: "1.0.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-example
  template:
    metadata:
      labels:
        app: node-example
        apm-enabled: "true"
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "node-example"
        tags.datadoghq.com/version: "1.0.0"
    spec:
      containers:
      - name: node-example
        image: nuttea/node-example:v8
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.25"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: DD_ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/env']
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/service']
          - name: DD_VERSION 
            valueFrom: 
              fieldRef: 
                fieldPath: metadata.labels['tags.datadoghq.com/version']
